In [4]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from statemanagers.hex_state_manager import HEXStateManager

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
K = 3
sm = HEXStateManager(K)
state = sm.get_initial_state()
# state[1:] = [0, 0, -1, 0, -1, 0, -1, 0, 0]
# state[1:] = [-1, 0, -1, 1, 1, 1, -1, -1, 0, 1, 0, 0, 1, -1, 0, 0]
state[1:] = [-1, 0, -1, 1, 1, -1, 0, 1, 0]
board = np.array(state[1:]).reshape(K, K)

pd.DataFrame(board)

def transform_state(state):
    board = np.array(state[1:]).reshape(K, K)
    print(board)
    board = board.T * -1
    print(board)
    return [state[0], *list(board.ravel())]


In [9]:
(board.ravel())[::-1] == (np.rot90(board, k=2).ravel())

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [30]:
sm.is_final([1, *list(board.ravel())])

False

In [35]:
new_state = transform_state(state)
# sm.render_state(state)
sm.render_state(new_state)


[[-1  0 -1]
 [ 1  1 -1]
 [ 0  1  0]]
[[ 1 -1  0]
 [ 0 -1 -1]
 [ 1  1  0]]
